version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - app3
    restart: unless-stopped

  app1:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=5000
    expose:
      - "5000"
    restart: unless-stopped

  app2:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=5000
    expose:
      - "5000"
    restart: unless-stopped

  app3:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=5000
    expose:
      - "5000"
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped